channels:
  - conda-forge
  - defaults
dependencies:
  - arviz
  - astropy
  - h5py
  - ipywidgets
  - numpy
  - jupyterlab
  - lalsuite
  - matplotlib
  - pymc=5
  - pytables
  - pytensor
  - seaborn
  - tqdm
